--화면 설계서 기준으로 dql/dml 작성
-- ui007 화면설계서 id -학생등록

--ui 008 학생 - 마이페이지
select STUDENT_NO, STUDENT_NAME, S.DEPARTMENT_NO,
-- d.DEPARTMENT_NAME, 
(SELECT DEPARTMENT_NAME from TB_DEPARTMENT d WHERE d.DEPARTMENT_NO = s.dEPARTMENT_NO) DEPARTMENT_NAME
,STUDENT_ADDRESS, ABSENCE_YN, COACH_PROFESSOR_NO
--, p.PROFESSOR_NAME
,(SELECT PROFESSOR_NAME from TB_PROFESSOR d WHERE d.PROFESSOR_NO = s.COACH_PROFESSOR_NO) PROFESSOR_NAME
FROM TB_STUDENT s
--JOIN tb_department d USING (s.DEPARTMENT_NO = d.DEPARTMENT_NO)
--JOIN TB_PROFESSOR p ON (S.COACH_PROFESSOR_NO = p.PROFESSOR_NO)
;

select * from TB_DEPARTMENT;
desc TB_DEPARTMENT;
desc TB_PROFESSOR;